export const CREATE_COMMENT_REQUEST = 'comment/CREATE_COMMENT_REQUEST';
export const CREATE_COMMENT_SUCCESS = 'comment/CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_FAILURE = 'comment/CREATE_COMMENT_FAILURE';
export const DELETE_COMMENT_REQUEST = 'comment/DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_SUCCESS = 'comment/DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAILURE = 'comment/DELETE_COMMENT_FAILURE';
export const SET_COMMENTS = 'comment/SET_COMMENTS';
