export const FETCH_ALL_POSTS_REQUEST = 'post/FETCH_POSTS_REQUEST';
export const FETCH_ALL_POSTS_SUCCESS = 'post/FETCH_POSTS_SUCCESS';
export const FETCH_ALL_POSTS_FAILURE = 'post/FETCH_POSTS_FAILURE';

export const FETCH_POST_REQUEST = 'post/FETCH_POST_REQUEST';
export const FETCH_POST_SUCCESS = 'post/FETCH_POST_SUCCESS';
export const FETCH_POST_FAILURE = 'post/FETCH_POST_FAILURE';

export const CREATE_POST_REQUEST = 'post/CREATE_POST_REQUEST';
export const CREATE_POST_SUCCESS = 'post/CREATE_POST_SUCCESS';
export const CREATE_POST_FAILURE = 'post/CREATE_POST_FAILURE';

export const UPDATE_POST_REQUEST = 'post/UPDATE_POST_REQUEST';
export const UPDATE_POST_SUCCESS = 'post/UPDATE_POST_SUCCESS';
export const UPDATE_POST_FAILURE = 'post/UPDATE_POST_FAILURE';
